name: My first github actions
on: [Push]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/set up-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pipinstall pytest
      - name: Run Tests
        run: |
          cd src
          python -m pytest addition.py
        
